### ISSUE TITLE
Support for GNOME 44

### ISSUE THREAD

**Issue by I-Iawk** [vinceliuice/Lavanda-gtk-theme#11]
The theme doesn't support "Enhanced Quick Settings" as you can see the [Wi-Fi] [Bluetooth] [VPN] and [Power Mode] are not working as intended in GNOME 44 per the screenshot below. 

When I come across additional bugs and I will update you as I encounter them.

![Screenshot from 2023-04-04 15-51-19](https://user-images.githubusercontent.com/11224011/229939625-d38bf493-10a0-4d63-82f5-85f1ec11ac76.jpg)

**Comment by vinceliuice** [comment]
No problem, I'll fix it

**Comment by I-Iawk** [comment]
Appears that when the mouse highlights over the minimize, maximize and close buttons in GNOME Files 44, the colours do not change.

![image](https://user-images.githubusercontent.com/11224011/230505519-15a5ff76-c5de-4c4f-ae7c-695841ee5fc2.png)

**Comment by I-Iawk** [comment]
Closing notifications have the same issue.

![image](https://user-images.githubusercontent.com/11224011/230506964-15fe28f1-bc77-4a31-bca8-6fadcf238b25.png)
