### ISSUE TITLE
Libadwaita doesn't work on Gnome 44

### ISSUE THREAD

**Issue by loulou64490** [vinceliuice/Lavanda-gtk-theme#16]
Please patch the gnomee 44 version

**Comment by vinceliuice** [comment]
Run ./install.sh -l

**Comment by loulou64490** [comment]
I did it but there is a bug with the file explorer which is in light theme when I put the dark mode

**Comment by vinceliuice** [comment]
Run './install.sh -c dark -l' to install the dark one for libadwaita

**Comment by loulou64490** [comment]
I did, but the problem may be with my operating system
At worst, no matter
Thank you Vinceliuice for developing incredible themes and good luck
