### ISSUE TITLE
Internal Error: Not enough space

### ISSUE THREAD

**Issue by myyc** [vinceliuice/Lavanda-gtk-theme#17]
gnome 44, arch linux, latest everything.

running `./install.sh -c dark -l` gives this

```
GNOME Shell 44.1
Installing '/home/user/.themes/Lavanda-Dark'...
Internal Error: Not enough space
Internal Error: Not enough space
Installing '/home/user/.themes/Lavanda-Sea-Dark'...
Internal Error: Not enough space
Internal Error: Not enough space

Link '/home/user/.themes/Lavanda-Dark/gtk-4.0' to '/home/user/.config/gtk-4.0' for libadwaita...

Done.
```

as a consequence, gtk3 theme is not applied.

**Comment by vinceliuice** [comment]
File system error. you have no enough space

**Comment by vinceliuice** [comment]
Clean up unused files and junk files, the number of files is too many and exceeds the record limit of the file system

**Comment by myyc** [comment]
> Clean up unused files and junk files, the number of files is too many and exceeds the record limit of the file system

that's not what's going on, `touch a; install a b` works without issues.

**Comment by myyc** [comment]
no idea what happened. i doubt i had edited anything but maybe i did. git reset and it works again.. apologies for the noise
