### ISSUE TITLE
Distro logo on top bar

### ISSUE THREAD

**Issue by NavTech270** [vinceliuice/Lavanda-gtk-theme#18]
I cannot see my Distro logo on my top bar with this theme? @vinceliuice 
 
![Screenshot from 2023-06-12 14-31-47](https://github.com/vinceliuice/Lavanda-gtk-theme/assets/62112451/118865dc-918c-4cc5-8d96-9c9a9431dcb5)

**Comment by vinceliuice** [comment]
What extension about this distro logo ?

**Comment by NavTech270** [comment]
I just use the `blur my shell extension` for the top bar @vinceliuice I believe it's the theme that for some odd reason erases the logo:

![image](https://github.com/vinceliuice/Lavanda-gtk-theme/assets/62112451/0502113b-36bb-4cb3-9b02-b8295ee609df)

**Comment by vinceliuice** [comment]
What's your desktop version and system version ?

**Comment by vinceliuice** [comment]
![截图 2023-06-14 10-36-19](https://github.com/vinceliuice/Lavanda-gtk-theme/assets/7604295/9e0c8883-2dda-4432-9541-6b19a025d0fc)
I did not add any icons for this button

**Comment by vinceliuice** [comment]
Just install `arc-menu` : https://extensions.gnome.org/extension/1228/arc-menu/

**Comment by NavTech270** [comment]
Would it be possible to add a Distro Logo as a new feature for people who cannot install "arc menu" as a default icon that appears when installing this theme? @vinceliuice

**Comment by vinceliuice** [comment]
Add support now

**Comment by NavTech270** [comment]
Thank you, that's perfect! @vinceliuice
