### ISSUE TITLE
Top panel transparency

### ISSUE THREAD

**Issue by PierreFrn** [vinceliuice/Lavanda-gtk-theme#2]
Hello, very nice theme !

I just have a small problem with the top panel transparency, as I use the dark theme with a quite light background there is a big contrast between the panel color and the windows when fullscreen.
I changed the value in `gnome-shell.css` to make the panel always opaque but I wondered if there was a way to have a dynamic transparency ?

Apart from this small issue, this theme is awesome !

**Comment by vinceliuice** [comment]
It gona need a extension to support dynamic transparency

**Comment by PierreFrn** [comment]
Ok thank you, I'll wait for one to be available for gnome 43 :)
