### ISSUE TITLE
Gnome 45 Update

### ISSUE THREAD

**Issue by EmptyVisual** [vinceliuice/Lavanda-gtk-theme#23]
Hi Vince, I love this theme, thank you for all your work.

Would it be possible to get a blackness tweak variant of this theme and also updated to gnome 45? 

Thanks so much

**Comment by vinceliuice** [comment]
Support 45 now

**Comment by EmptyVisual** [comment]
> Support 45 now

Thank you! Compact mode is still broken in 45

Settings options look very large & shell top bar is still normal size (when using compact theme)


![image](https://github.com/vinceliuice/Lavanda-gtk-theme/assets/4710051/4c4a06ee-6d1d-4583-871f-22b09fde8df4)

**Comment by vinceliuice** [comment]
Now it's ok !

**Comment by EmptyVisual** [comment]
> Now it's ok !

Thank you Vince! Looks good, I'll send a donation your way <3

**Comment by vinceliuice** [comment]
Thank you for your donation!
