### ISSUE TITLE
Notifications in GNOME 46 aren't visible

### ISSUE THREAD

**Issue by SVTA-OP** [vinceliuice/Lavanda-gtk-theme#32]
After GNOME 46 updated the notification cards, they aren't visible when using the lavanda-sea-dark gtk theme.  
  
  
This is default adwaita  
![20240428_102557](https://github.com/vinceliuice/Lavanda-gtk-theme/assets/126323835/a3c3c16f-0f3e-4c79-ad9c-a2596517577a)  

  
This is lavanda  
![20240428_102711](https://github.com/vinceliuice/Lavanda-gtk-theme/assets/126323835/5b4892ee-7a17-4be3-b5b0-9c4de5b33307)

**Comment by vinceliuice** [comment]
Download the last update and try again

**Comment by SVTA-OP** [comment]
Fixed the problem thanks.
