### ISSUE TITLE
Theme no longer applied to libadwaita applications after reboot

### ISSUE THREAD

**Issue by Buuugle** [vinceliuice/Lavanda-gtk-theme#35]
I installed this theme with the "-l" option to apply it to libadwaita applications, such as nautilus. This works, but after restarting the computer, the theme is no longer applied to these applications. I have to reinstall the theme with the "-l" option to apply it again until the next reboot.
I don't know if it helps, but I use Fedora 39 on Gnome with Wayland.

**Comment by vinceliuice** [comment]
Did you installed any theme custom extension like Custom Accent Colors ...

**Comment by Buuugle** [comment]
I uninstalled Custom Accent Colors, that was indeed the problem. Thanks for your help!
